/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO0_29 (number 92), P8[2]/U6[13]/FC0_USART_RXD
  @{ */
#define DEBUG_UART_RX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define DEBUG_UART_RX_PIN 29U                   /*!<@brief PORT pin number */
#define DEBUG_UART_RX_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO0_30 (number 94), P8[3]/U6[12]/FC0_USART_TXD
  @{ */
#define DEBUG_UART_TX_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define DEBUG_UART_TX_PIN 30U                   /*!<@brief PORT pin number */
#define DEBUG_UART_TX_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_4 (number 1), R78/P18[5]/LEDR/PWM_ARD
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_BLUE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define LED_BLUE_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define LED_BLUE_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define LED_BLUE_PIN 4U                   /*!<@brief PORT pin number */
#define LED_BLUE_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PIO1_6 (number 5), R80/P18[9]/LEDB/PWM_ARD
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define LED_RED_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define LED_RED_PIN 6U                   /*!<@brief PORT pin number */
#define LED_RED_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PIO1_7 (number 9), R79/P18[7]/LEDG/PWM_ARD
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_GREEN_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define LED_GREEN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define LED_GREEN_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define LED_GREEN_PIN 7U                   /*!<@brief PORT pin number */
#define LED_GREEN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Pull-up current source enable in I2C mode.: Enabled. Pull resistor is conencted. */
#define PIO0_13_ECS_ENABLED 0x01u
/*!
 * @brief Switch between GPIO mode and I2C mode.: I2C mode. */
#define PIO0_13_EGP_I2C_MODE 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_13_FUNC_ALT1 0x01u
/*!
 * @brief
 * Configures I2C features for standard mode, fast mode, and Fast Mode Plus operation and High-Speed mode
 * operation.
 * : I2C 10 ns glitch filter enabled.
 * Typically used for High-speed mode I2C.
 */
#define PIO0_13_I2CFILTER_STANDARD_MODE 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_13_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Controls open-drain mode in standard GPIO mode (EGP = 1).
 * This bit has no effect in I2C mode (EGP=0).
 * : Normal.
 * Normal push-pull output.
 */
#define PIO0_13_OD_NORMAL 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO0_13_SLEW_STANDARD 0x00u
/*!
 * @brief Supply Selection bit.: 3V3 Signaling in I2C Mode. */
#define PIO0_13_SSEL_SEL3V3 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Pull-up current source enable in I2C mode.: Enabled. Pull resistor is conencted. */
#define PIO0_14_ECS_ENABLED 0x01u
/*!
 * @brief Switch between GPIO mode and I2C mode.: I2C mode. */
#define PIO0_14_EGP_I2C_MODE 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO0_14_FUNC_ALT1 0x01u
/*!
 * @brief
 * Configures I2C features for standard mode, fast mode, and Fast Mode Plus operation and High-Speed mode
 * operation.
 * : I2C 10 ns glitch filter enabled.
 * Typically used for High-speed mode I2C.
 */
#define PIO0_14_I2CFILTER_STANDARD_MODE 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_14_MODE_PULL_UP 0x02u
/*!
 * @brief
 * Controls open-drain mode in standard GPIO mode (EGP = 1).
 * This bit has no effect in I2C mode (EGP=0).
 * : Normal.
 * Normal push-pull output.
 */
#define PIO0_14_OD_NORMAL 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO0_14_SLEW_STANDARD 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_10_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_10_MODE_PULL_DOWN 0x01u
/*!
 * @brief Controls open-drain mode.: Normal. Normal push-pull output */
#define PIO1_10_OD_NORMAL 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard-mode, output slew rate is slower.
 * More outputs can be switched simultaneously.
 */
#define PIO1_10_SLEW_STANDARD 0x00u

/*! @name PIO0_13 (number 71), P19[9]/P19[10]/U2[E6]/P20[8]/FC1_I2C_SDA
  @{ */
#define I2C_SDA_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define I2C_SDA_PIN 13U                   /*!<@brief PORT pin number */
#define I2C_SDA_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PIO0_14 (number 72), P19[11]/P19[12]/U2[D6]/P20[6]/FC1_I2C_SCL
  @{ */
#define I2C_SCL_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define I2C_SCL_PIN 14U                   /*!<@brief PORT pin number */
#define I2C_SCL_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PIO1_10 (number 40), P18[3]/PIO1_10_GPIO_ARD
  @{ */
#define MPU6050_INT_Pin_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define MPU6050_INT_Pin_PIN 10U                   /*!<@brief PORT pin number */
#define MPU6050_INT_Pin_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core0(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
